/**
 * Catálogo de obras de Denise.
 *
 * Para agregar una obra nueva:
 *   1. Copiar uno de los objetos de abajo.
 *   2. Completar todos los campos.
 *   3. Agregar las imágenes en assets/images/<carpeta>/.
 *   4. El campo `id` debe ser único y sin espacios (ej: 'mi-nueva-obra').
 *
 * imagenPosicion: valor CSS de object-position ('center', 'top', '70% 90%', etc.)
 * Cada entrada en `imagenes` puede ser un string o { src, posicion }.
 */

const OBRAS = [
  {
    id: 'david',
    titulo: 'Gemelo Digital "El David" de Miguel Ángel',
    coleccion: 'David',
    material: 'Resina',
    año: '2024',
    dimensiones: '5,17 m de altura',
    descripcion: 'Réplica a escala real realizada con tecnología 4.0 por encargo de la Fundación Urunday para la Bienal Internacional de Escultura del Chaco. Emplazada en el Domo del Centenario, Resistencia, Chaco, Argentina.\n\nEsta obra monumental nace de un proceso de digitalización 3D de alta precisión del calco certificado de El David de Miguel Ángel, ubicado en el Museo de la Cárcova (Buenos Aires). Se trató de un procedimiento novedoso no invasivo, que permitió generar un gemelo digital exacto de la pieza original.\n\nA partir de ese modelo se aplicaron procesos de manufactura aditiva (impresión 3D) para la fabricación de moldes, integrando tecnología avanzada con técnicas escultóricas tradicionales. Un proyecto que combina arte, patrimonio y tecnología contemporánea en una escala excepcional.\n\nRealizado en colaboración con la escultora Gisela Kraisman.\nEquipo de trabajo: María Soto, Ricardo Soto, Facundo Álvarez, Adrián Vigil, Marcelo Santillán.',
    imagenPosicion: 'top',
    imagenPrincipal: './assets/images/david/01.jpg',
    imagenes: [
      { src: './assets/images/david/01.jpg', posicion: 'top' },
      { src: './assets/images/david/02.jpg', posicion: 'top' },
      { src: './assets/images/david/03.jpg', posicion: 'top' },
      './assets/images/david/04.jpg',
      './assets/images/david/05.jpg',
      './assets/images/david/06.jpg',
      './assets/images/david/07.jpg',
      './assets/images/david/08.jpg',
      './assets/images/david/09.jpg',
      './assets/images/david/10.jpg',
      './assets/images/david/11.jpg',
      './assets/images/david/12.jpg',
      './assets/images/david/13.jpg',
      './assets/images/david/14.jpg',
      './assets/images/david/15.jpg',
      './assets/images/david/16.jpg',
      { src: './assets/images/david/17.jpg', posicion: 'top' },
      { src: './assets/images/david/18.jpg', posicion: 'top' },
    ],
  },
  {
    id: 'convergencia-diptico',
    titulo: 'Convergencia',
    coleccion: 'Ninfas',
    material: 'Ensamble digital impreso en PLA',
    año: '2025',
    dimensiones: '130 × 116 × 26 cm',
    descripcion: 'Este díptico indaga una pregunta central: ¿Cómo se redefine el vínculo cuerpo–naturaleza siendo, al mismo tiempo, seres tecnológicos?\n\nLas ninfas aparecen como símbolo de una unión primigenia, atravesadas por el lenguaje tecnológico actual.\n\nDos cuerpos se aproximan sin terminar de tocarse. El gesto suspendido construye un umbral: un espacio indefinido donde lo orgánico y lo tecnológico dialogan.',
    imagenPrincipal: './assets/images/convergencia/01.jpg',
    imagenes: [
      './assets/images/convergencia/01.jpg',
      './assets/images/convergencia/02.jpg',
      './assets/images/convergencia/03.jpg',
      './assets/images/convergencia/04.jpg',
      './assets/images/convergencia/05.jpg',
      './assets/images/convergencia/06.jpg',
    ],
  },
  {
    id: 'serie-driadas',
    titulo: 'Serie Las dríadas ',
    coleccion: 'Ninfas',
    material: 'Impresión 3D en Wood. 2026',
    año: '2025–26',
    dimensiones: '190cm x 172cm x100cm.',
    descripcion: 'Dicen que, cuando el bosque cambia de piel, las ninfas aprenden a renacer.\n\nLas fibras de pino que alguna vez fueron árbol emergen desde la máquina, reclamando su cuerpo mítico: surgen del encuentro fantástico entre lo natural y lo tecnológico, allí donde ambos mundos se entrelazan.',
    imagenPosicion: '10% 90%',
    imagenPrincipal: './assets/images/serie-driadas/1_Serie driadas.jpg',
    imagenes: [
      './assets/images/serie-driadas/1_Serie driadas.jpg',
      './assets/images/serie-driadas/2_Serie driadas.jpg',
      './assets/images/serie-driadas/3_Serie driadas.jpg',
      './assets/images/serie-driadas/4_Serie driadas.jpg',
      './assets/images/serie-driadas/5_Serie driadas.jpg',
      './assets/images/serie-driadas/6_Serie driadas.jpg',
      './assets/images/serie-driadas/7_Serie driadas.jpg',
      './assets/images/serie-driadas/8_Serie driadas.jpg',
      './assets/images/serie-driadas/9_Serie driadas.jpg',
      './assets/images/serie-driadas/10_Serie driadas.jpg',
      './assets/images/serie-driadas/11_Serie driadas.jpg',
      './assets/images/serie-driadas/B1_Detalle.jpg',
      './assets/images/serie-driadas/B2_Detalle.jpg',
      './assets/images/serie-driadas/B3_Detalle.jpg',
      './assets/images/serie-driadas/B4_Detalle.jpg',
    ],
  },
  {
    id: 'driada-en-las-piedras',
    titulo: 'Dríada en las Piedras',
    coleccion: 'Ninfas',
    material: 'Ensamble digital impreso en PLA',
    año: '2024',
    dimensiones: '357 × 234 × 110 mm',
    descripcion: 'En esta pieza exploro la figura de la dríada como cuerpo que emerge y se funde con la materia.\n\nLa forma no descansa sobre la piedra: parece surgir y disolverse en ella al mismo tiempo.',
    imagenPrincipal: './assets/images/driada-piedras/01.jpg',
    imagenes: [
      './assets/images/driada-piedras/01.jpg',
      './assets/images/driada-piedras/02.jpg',
      './assets/images/driada-piedras/03.jpg',
      './assets/images/driada-piedras/04.jpg',
      './assets/images/driada-piedras/05.jpg',
      './assets/images/driada-piedras/06.jpg',
      './assets/images/driada-piedras/07.jpg',
    ],
  },
  {
    id: 'variaciones',
    titulo: 'Variaciones',
    coleccion: 'Ninfas',
    material: 'Díptico Ensamble digital impreso en PLA y pintura acrílica',
    año: '2024',
    dimensiones: 'Díptico. Cada relieve 27 × 14 × 5 cm',
    descripcion: 'Dos relieves idénticos, dos presencias autónomas.\n\nA partir de un mismo modelo virtual como matriz, la forma se repite sin ser la misma.\n\nLa variación no altera la estructura, pero modifica su modo de aparecer.',
    imagenPrincipal: './assets/images/variaciones/01.jpg',
    imagenes: [
      './assets/images/variaciones/01.jpg',
      './assets/images/variaciones/02.jpg',
      './assets/images/variaciones/03.jpg',
      './assets/images/variaciones/04.jpg',
      './assets/images/variaciones/05.jpg',
      './assets/images/variaciones/06.jpg',
    ],
  },
  {
    id: 'materia-sin-materializar',
    titulo: 'Materia sin material',
    coleccion: 'Obra virtual',
    material: 'Ensamble digital (obra virtual)',
    año: '2024',
    dimensiones: 'Medida variable',
    descripcion: 'Estas composiciones forman parte de un proceso de exploración digital previo a la materialización. Son ensayos tridimensionales donde investigo fragmentación, composición y gesto a través de herramientas de modelado y digitalización 3D.\n\nAquí el cuerpo se desarma, se multiplica, se incrusta, fusiona o emerge desde la superficie. La materia aún no existe físicamente, pero ya anticipa tensiones formales y decisiones futuras.\n\nMás que obras concluidas, son territorios de prueba: espacios donde la figura se redefine antes de convertirse en objeto.\n\nSerie compuesta por: Composición 3, Multiplicidad, Fuente y Composición 2B.',
    imagenPrincipal: './assets/images/materia-virtual/01.jpg',
    imagenes: [
      './assets/images/materia-virtual/01.jpg',
      './assets/images/materia-virtual/02.jpg',
      './assets/images/materia-virtual/03.jpg',
      './assets/images/materia-virtual/04.jpg',
      './assets/images/materia-virtual/05.jpg',
      './assets/images/materia-virtual/06.jpg',
      './assets/images/materia-virtual/07.jpg',
      './assets/images/materia-virtual/08.jpg',
      './assets/images/materia-virtual/09.jpg',
      './assets/images/materia-virtual/10.jpg',
      './assets/images/materia-virtual/11.jpg',
      './assets/images/materia-virtual/12.jpg',
    ],
  },
];
