/**
 * Catálogo de obras de Denise.
 *
 * Para agregar una obra nueva:
 *   1. Copiar uno de los objetos de abajo.
 *   2. Completar todos los campos.
 *   3. Agregar las imágenes en assets/images/<carpeta>/.
 *   4. El campo `id` debe ser único y sin espacios (ej: 'mi-nueva-obra').
 *
 * imagenPosicion: valor CSS de object-position ('center', 'top', '70% 90%', etc.)
 * Cada entrada en `imagenes` puede ser un string o { src, posicion }.
 */

const OBRAS = [
  {
    id: 'david',
    titulo: 'Gemelo Digital "El David" de Miguel Ángel',
    coleccion: 'David',
    material: 'Resina con aditivos especiales',
    año: '2024',
    dimensiones: '5,17 m de altura',
    descripcion: 'Réplica a escala real realizada con tecnología 4.0 por encargo de la Fundación Urunday para la Bienal Internacional de Escultura del Chaco. Emplazada en el Domo del Centenario, Resistencia, Chaco, Argentina.\n\nEsta obra monumental nace de un proceso de digitalización 3D de alta precisión del calco certificado de El David de Miguel Ángel, ubicado en el Museo de la Cárcova (Buenos Aires). Se trató de un procedimiento novedoso no invasivo, que permitió generar un gemelo digital exacto de la pieza original.\n\nA partir de ese modelo se aplicaron procesos de manufactura aditiva (impresión 3D) para la fabricación de moldes, integrando tecnología avanzada con técnicas escultóricas tradicionales. Un proyecto que combina arte, patrimonio y tecnología contemporánea en una escala excepcional.\n\nRealizado en colaboración con la escultora Gisela Kraisman.\nEquipo de trabajo: María Soto, Ricardo Soto, Facundo Álvarez, Adrián Vigil, Marcelo Santillán.',
    imagenPosicion: 'top',
    imagenPrincipal: './assets/images/david/01.jpg',
    imagenes: [
      { src: './assets/images/david/01.jpg', posicion: 'top' },
      { src: './assets/images/david/02.jpg', posicion: 'top' },
      { src: './assets/images/david/03.jpg', posicion: 'top' },
      './assets/images/david/04.jpg',
      './assets/images/david/05.jpg',
      './assets/images/david/06.jpg',
      './assets/images/david/07.jpg',
      './assets/images/david/08.jpg',
      './assets/images/david/09.jpg',
      './assets/images/david/10.jpg',
      './assets/images/david/11.jpg',
      './assets/images/david/12.jpg',
      './assets/images/david/13.jpg',
      './assets/images/david/14.jpg',
      './assets/images/david/15.jpg',
      './assets/images/david/16.jpg',
      { src: './assets/images/david/17.jpg', posicion: 'top' },
      { src: './assets/images/david/18.jpg', posicion: 'top' },
    ],
  },
  {
    id: 'convergencia-diptico',
    titulo: 'Convergencia. Díptico',
    coleccion: 'Ninfas',
    material: 'Impresión 3D en PLA',
    año: '2025',
    dimensiones: '130 × 116 × 26 cm',
    descripcion: 'En esta obra investigo el vínculo entre cuerpo y naturaleza desde una mirada contemporánea. Las ninfas aparecen como símbolo de esa unión primigenia, atravesadas por el lenguaje tecnológico actual.\n\nDos cuerpos se aproximan sin terminar de tocarse. El gesto suspendido construye un umbral: un espacio indefinido donde lo orgánico y lo tecnológico dialogan.\n\nLas figuras, surgidas de escaneos 3D y procesos de impresión en PLA, conservan la memoria de la tradición escultórica mientras revelan su origen digital. La estructura interna hexagonal expuesta no se oculta: forma parte del lenguaje y evidencia el sistema que sostiene la forma.\n\nLa obra indaga una pregunta central: ¿Cómo se redefine el vínculo cuerpo–naturaleza siendo, al mismo tiempo, seres tecnológicos?',
    imagenPrincipal: './assets/images/convergencia/01.jpg',
    imagenes: [
      './assets/images/convergencia/01.jpg',
      './assets/images/convergencia/02.jpg',
      './assets/images/convergencia/03.jpg',
      './assets/images/convergencia/04.jpg',
      './assets/images/convergencia/05.jpg',
      './assets/images/convergencia/06.jpg',
    ],
  },
  {
    id: 'ninfas-de-hoy',
    titulo: '¿En qué paisaje surgen las Ninfas de hoy?',
    coleccion: 'Ninfas',
    material: 'Impresión 3D en madera plástica',
    año: '2025–26',
    dimensiones: '100 × 25 × 40–70 cm (variable)',
    descripcion: 'En esta serie de esculturas, las Dríadas dejan de pertenecer al mito antiguo para aparecer como seres híbridos, nacidos en un territorio donde lo natural y lo tecnológico se entrelazan. Evocadas como figuras capaces de imaginar nuevas formas de vida en un paisaje transformado.\n\nTrabajo con madera-plástica —un material biodegradable compuesto por fibras reales de pino— que lleva en sí la memoria del árbol, pero se materializa a través de la precisión de la impresión 3D. Ese cruce activa una tensión que me interesa: fibras que alguna vez fueron árbol reclamando, desde la máquina, un cuerpo mítico posible.\n\nLos escaneos 3D de cuerpos y objetos reales operan como mi arcilla digital. A partir de ellos, ensayo transiciones entre piel, hoja, corteza y superficie tecnológica; ensamblando fragmentos que no imitan la naturaleza, sino que proponen futuros posibles para ella.\n\nConcibo estas esculturas como un bosque inventado, habitado por presencias que insisten en existir aun en un mundo en transición.',
    imagenPosicion: '10% 90%',
    imagenPrincipal: './assets/images/ninfas/01.jpg',
    imagenes: [
      './assets/images/ninfas/01.jpg',
      './assets/images/ninfas/02.jpg',
      './assets/images/ninfas/03.jpg',
      './assets/images/ninfas/04.jpg',
      './assets/images/ninfas/05.jpg',
      './assets/images/ninfas/06.jpg',
    ],
  },
  {
    id: 'driada-en-las-piedras',
    titulo: 'Dríada en las Piedras',
    coleccion: 'Ninfas',
    material: 'Impresión 3D en PLA',
    año: '2024',
    dimensiones: '357 × 234 × 110 mm',
    descripcion: 'En esta pieza exploro la figura de la dríada como cuerpo que emerge y se funde con la materia. La forma no descansa sobre la piedra: parece surgir y disolverse en ella al mismo tiempo.\n\nRealizada a partir de escaneos 3D e impresión en PLA, la obra conserva la memoria del gesto escultórico tradicional mientras incorpora el lenguaje técnico de su proceso. Lo orgánico y lo estructural no se enfrentan: se integran en una única presencia.\n\nUna investigación sobre el cuerpo como extensión de la naturaleza y como territorio atravesado por la tecnología.',
    imagenPrincipal: './assets/images/driada-piedras/01.jpg',
    imagenes: [
      './assets/images/driada-piedras/01.jpg',
      './assets/images/driada-piedras/02.jpg',
      './assets/images/driada-piedras/03.jpg',
      './assets/images/driada-piedras/04.jpg',
      './assets/images/driada-piedras/05.jpg',
      './assets/images/driada-piedras/06.jpg',
      './assets/images/driada-piedras/07.jpg',
    ],
  },
  {
    id: 'variaciones',
    titulo: 'Variaciones',
    coleccion: 'Ninfas',
    material: 'PLA e impresión 3D. Pintura acrílica',
    año: '2024',
    dimensiones: 'Díptico. Cada relieve 27 × 14 × 5 cm',
    descripcion: 'Dos relieves idénticos, dos presencias autónomas.\n\nA partir de un mismo modelo virtual como matriz, la forma se repite sin ser la misma. La variación no altera la estructura, pero modifica su modo de aparecer.\n\nUn estudio sobre repetición y diferencia: cómo una misma figura puede devenir múltiples estados.',
    imagenPrincipal: './assets/images/variaciones/01.jpg',
    imagenes: [
      './assets/images/variaciones/01.jpg',
      './assets/images/variaciones/02.jpg',
      './assets/images/variaciones/03.jpg',
      './assets/images/variaciones/04.jpg',
      './assets/images/variaciones/05.jpg',
      './assets/images/variaciones/06.jpg',
    ],
  },
  {
    id: 'materia-sin-materializar',
    titulo: 'Materia sin materializar',
    coleccion: 'Obra virtual',
    material: 'Ensamble digital (obra virtual)',
    año: '2024',
    dimensiones: 'Medida variable',
    descripcion: 'Estas composiciones forman parte de un proceso de exploración digital previo a la materialización. Son ensayos tridimensionales donde investigo fragmentación, composición y gesto a través de herramientas de modelado y digitalización 3D.\n\nAquí el cuerpo se desarma, se multiplica, se incrusta, fusiona o emerge desde la superficie. La materia aún no existe físicamente, pero ya anticipa tensiones formales y decisiones futuras.\n\nMás que obras concluidas, son territorios de prueba: espacios donde la figura se redefine antes de convertirse en objeto.\n\nSerie compuesta por: Composición 3, Multiplicidad, Fuente y Composición 2B.',
    imagenPrincipal: './assets/images/materia-virtual/01.jpg',
    imagenes: [
      './assets/images/materia-virtual/01.jpg',
      './assets/images/materia-virtual/02.jpg',
      './assets/images/materia-virtual/03.jpg',
      './assets/images/materia-virtual/04.jpg',
      './assets/images/materia-virtual/05.jpg',
      './assets/images/materia-virtual/06.jpg',
      './assets/images/materia-virtual/07.jpg',
      './assets/images/materia-virtual/08.jpg',
      './assets/images/materia-virtual/09.jpg',
      './assets/images/materia-virtual/10.jpg',
      './assets/images/materia-virtual/11.jpg',
      './assets/images/materia-virtual/12.jpg',
    ],
  },
];
